/*
 * Copyright 2015 Tom Gibara
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
package com.tomgibara.hashing;

import java.security.MessageDigest;

/**
 * Generates digests from which hashes may be derived.
 *
 * @author Tom Gibara
 *
 */

@FunctionalInterface
public interface HashDigest {

	/**
	 * Creates a new message digest instance
	 *
	 * @return a digest
	 */
	MessageDigest newDigest();

	/**
	 * Derives a hash from the digest. The {@link HashSize} of the resulting
	 * hash is determined by the length of the digest.
	 *
	 * @return a {@link Hash} implementation that uses the digests generated by
	 *         this source to derive the hash values.
	 */

	default Hash asHash() {
		return new DigestHash(this);
	}

}